name: redeploy

on:
  schedule:
    - cron: '*/5 * * * *' #at 10:30 UTC (6:30 EST) each morning

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: cmillward13/fetch-url@1.0
      with:
        url: 'https://api.vercel.com/v1/integrations/deploy/prj_y9Z6HJAZ5OwSGL0L2Emio3y6qbhg/MH1nIGMQPW'
      id: fetcher
      
    - name: afterDeploy
      if: steps.fetcher.outputs.completeed == 'true'
      run: echo "Site Re-deployed"
