name: redeploy

on:
  schedule: 
    - cron: '0 13,14 * * *' #(8:00, and 10:00 EST) each morning

jobs:
  redeploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: boyeborg/fetch-url-action@v1.1
      with:
        url: 'https://api.vercel.com/v1/integrations/deploy/prj_y9Z6HJAZ5OwSGL0L2Emio3y6qbhg/MH1nIGMQPW'
      
